version: '3.1'

services:

  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
        # you may set custom IP addresses
        back:
            ipv4_address: 172.16.238.11 
            ipv6_address: "2001:3984:3989::11"

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: alvaro
      MYSQL_DATABASE: pa_virtual
      MYSQL_USER: alvaro
      MYSQL_PASSWORD: alvaro
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
        # you may set custom IP addresses    
      back:
        ipv4_address: 172.16.238.12 
        ipv6_address: "2001:3984:3989::12"
networks:
    back:
        # use the bridge driver, but enable IPv6
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1
                - subnet: "2001:3984:3989::/64"
                  gateway: "2001:3984:3989::1"