version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: alvaro
      MYSQL_DATABASE: pa_virtual
      MYSQL_USER: alvaro
      MYSQL_PASSWORD: alvaro
    volumes:
      - ./mysql_data:/var/lib/mysql
